site :opscode
cookbook "yum", "~> 3.0.0"
cookbook "yum-epel"
cookbook "yum-repoforge"
cookbook "yum-remi", git: "https://github.com/tektoh/yum-remi.git"
cookbook "selinux"
cookbook "iptables"
cookbook "git"
cookbook "php"
cookbook "mysql"
cookbook "apache2"
cookbook "memcached"
cookbook "composer"
cookbook "nodejs"
cookbook "phpmyadmin"
cookbook "i18n", git: "https://github.com/tektoh/centos-i18n.git"
cookbook "devtools", git: "https://github.com/tektoh/centos-devtools.git"
cookbook "webserver", path: "site-cookbooks/webserver"
cookbook "php-extends", path: "site-cookbooks/php-extends"